### ISSUE TITLE
Why is there a module parse failed error?

### ISSUE THREAD

**Issue by thepoppingone** [compulim/react-sanitized-html#2]
ERROR in ./~/react-sanitized-html/index.js
Module parse failed: Unexpected token (38:6)
You may need an appropriate loader to handle this file type.
|
|     return (
|       <div
|         className={ this.props.className }
|         dangerouslySetInnerHTML={{ __html: sanitizedHTML }}

**Comment by compulim** [comment]
You can look at https://github.com/compulim/react-sanitized-html-testbed to see how to use it.
